name: k8sD


on:
  push:
    branches:
      - main
env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
#  K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE }}
#  K8S_SERVER: ${{ secrets.K8S_SERVER }}
#  K8S_TOKEN: ${{ secrets.K8S_TOKEN }}
#  K8S_CA: ${{ secrets.K8S_CA }}
#  K8S_CLUSTER: ${{ secrets.K8S_CLUSTER }}
#  K8S_CONTEXT: ${{ secrets.K8S_CONTEXT }}
#  K8S_USER: ${{ secrets.K8S_USER }}
#  K8S_PASSWORD: ${{ secrets.K8S_PASSWORD }}
#  K8S_SERVICE: ${{ secrets.K8S_SERVICE }}
#  K8S_PORT: ${{ secrets.K8S_PORT }}
#  K8S_PROTOCOL: ${{ secrets.K8S_PROTOCOL }}
#  K8S_CERT: ${{ secrets.K8S_CERT }}
#  K8S_KEY: ${{ secrets.K8S_KEY }}
#  K8S_CA_DATA: ${{ secrets.K8S_CA_DATA }}
#  K8S_CERT_DATA: ${{ secrets.K8S_CERT_DATA }}
#  K8S_KEY_DATA: ${{ secrets.K8S_KEY_DATA }}
#  K8S_SERVICE_ACCOUNT: ${{ secrets.K8S_SERVICE_ACCOUNT }}
#  K8S_SERVICE_ACCOUNT_SECRET: ${{ secrets.K8S_SERVICE_ACCOUNT_SECRET }}
#  K8S_SERVICE_ACCOUNT_SECRET_DATA: ${{ secrets.K8S_SERVICE_ACCOUNT_SECRET_DATA }}
#  K8S_SERVICE_ACCOUNT_SECRET_NAME: ${{ secrets.K8S_SERVICE_ACCOUNT_SECRET_NAME }}
#  K8S_SERVICE_ACCOUNT_SECRET_NAMESPACE: ${{ secrets.K8S_SERVICE_ACCOUNT_SECRET_NAMESPACE }}
#  K8S_SERVICE_ACCOUNT_SECRET_DATA_KEY: ${{ secrets.K8S_SERVICE_ACCOUNT_SECRET_DATA_KEY }}
#  K8S_SERVICE_ACCOUNT_SECRET_DATA_VALUE: ${{ secrets.K8S_SERVICE_ACCOUNT_SECRET_DATA_VALUE }}
#  K8S_SERVICE_ACCOUNT_SECRET_DATA_CA: ${{ secrets.K8S_SERVICE_ACCOUNT_SECRET_DATA_CA }}
#  K8S_SERVICE_ACCOUNT_SECRET_DATA_CERT: ${{ secrets.K8S_SERVICE_ACCOUNT_SECRET_DATA_CERT }}
#  K8S_SERVICE_ACCOUNT_SECRET_DATA_KEY: ${{ secrets.K8S_SERVICE_ACCOUNT_SECRET_DATA_KEY }}
#  K8S_SERVICE_ACCOUNT_SECRET_DATA_TOKEN: ${{ secrets.K8S_SERVICE_ACCOUNT_SECRET_DATA_TOKEN }}
#  K8S_SERVICE_ACCOUNT_SECRET_DATA_USERNAME: ${{ secrets.K8S_SERVICE_ACCOUNT_SECRET_DATA_USERNAME }}
#  K8S_SERVICE_ACCOUNT_SECRET_DATA_PASSWORD

jobs: 
  deploy:
    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy Dev Namespace
        uses: actions-hub/kubectl@master
        with:
          args: apply -f Manifests/
